apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: connected-fleet
spec:
  baseDomain: example.test
  ocpInstallType: connected
  secrets:
    openshift-pull-secret:
      file: ~/.bootwright/secrets/openshift-pull-secret
    cluster-admin-key:
      file: ~/.ssh/bootwright-ssh-key.pub
    libvirt-host-ssh:
      file: ~/.ssh/bootwright-ssh-key
    libvirt-redfish-bmc:
      generated:
        credentials:
          username: admin
    baremetal-redfish-bmc:
      generated:
        credentials:
          username: admin
  openshift:
    release:
      channel: stable-4.21
      version: 4.21.12
