---
bootwright_secrets_dir: "{{ lookup('env', 'BOOTWRIGHT_SECRETS_DIR') | default((lookup('env', 'BOOTWRIGHT_USER_DIR') | default(lookup('env', 'HOME') ~ '/.bootwright', true)) ~ '/secrets', true) }}"

bootwright_openshift_install: openshift-install

bootwright_ocp_install_timeout_seconds: 5400
