apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: edge-lb-env
spec:
  baseDomain: example.test
  ocpInstallType: connected
  secrets:
    openshift-pull-secret:
      file: ~/.bootwright/secrets/openshift-pull-secret
    cluster-admin-key:
      file: ~/.ssh/bootwright-ssh-key.pub
    edge-host-ssh:
      file: ~/.ssh/bootwright-ssh-key
    baremetal-redfish-bmc:
      generated:
        credentials:
          username: admin
