apiVersion: gitups.io/v1alpha1
kind: OCPCluster
metadata:
  name: managed
spec:
  topology: single-node
  infrastructureRef:
    name: managed
  install:
    method: agent
  nodes:
    master-0:
      role: control-plane
