---
- name: Install controller OpenShift CLIs
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  tasks:
    - name: Install requested OpenShift CLI release
      ansible.builtin.import_role:
        name: ocp_clis
