apiVersion: gitups.io/v1alpha1
kind: InfrastructureProvider
metadata:
  name: lab-hub-provider
spec:
  hosts:
    hub-sno-host:
      ssh:
        address: 10.10.10.1
        user: gitups
        keyRef:
          name: lab-provider-key
      capabilities:
        - libvirt
        - hosts-file
  machine:
    libvirt:
      hostRefs:
        - name: hub-sno-host
      bmcEmulation:
        enabled: true
        protocol: redfish
        port: 8000
        auth:
          credentialRef:
            name: lab-bmc-credentials
  loadBalancer:
    haProxy:
      hostRef:
        name: hub-sno-host
  nameResolution:
    hostsFile:
      hostRefs:
        - name: hub-sno-host
---
apiVersion: gitups.io/v1alpha1
kind: InfrastructureProvider
metadata:
  name: lab-spoke-01-provider
spec:
  hosts:
    spoke-01-host:
      ssh:
        address: 10.10.10.2
        user: gitups
        keyRef:
          name: lab-provider-key
      capabilities:
        - libvirt
        - hosts-file
  machine:
    libvirt:
      hostRefs:
        - name: spoke-01-host
      bmcEmulation:
        enabled: true
        protocol: redfish
        port: 8000
        auth:
          credentialRef:
            name: lab-bmc-credentials
  loadBalancer:
    haProxy:
      hostRef:
        name: spoke-01-host
  nameResolution:
    hostsFile:
      hostRefs:
        - name: spoke-01-host
---
apiVersion: gitups.io/v1alpha1
kind: InfrastructureProvider
metadata:
  name: lab-spoke-02-provider
spec:
  hosts:
    spoke-02-host:
      ssh:
        address: 10.10.10.3
        user: gitups
        keyRef:
          name: lab-provider-key
      capabilities:
        - libvirt
        - hosts-file
  machine:
    libvirt:
      hostRefs:
        - name: spoke-02-host
      bmcEmulation:
        enabled: true
        protocol: redfish
        port: 8000
        auth:
          credentialRef:
            name: lab-bmc-credentials
  loadBalancer:
    haProxy:
      hostRef:
        name: spoke-02-host
  nameResolution:
    hostsFile:
      hostRefs:
        - name: spoke-02-host
