apiVersion: gitups.io/v1alpha1
kind: ClusterInfrastructure
metadata:
  name: spoke-01
spec:
  providerRef:
    name: lab-spoke-01-provider
  networks:
    primary:
      cidr: 192.168.123.0/24
      gateway: 192.168.123.1
      dnsServers:
        - 192.168.123.1
      libvirt:
        bridge: vbr-spoke-01
  machines:
    master-0:
      interfaces:
        primary:
          networkRef:
            name: primary
          ipAddress: 192.168.123.20
      libvirt:
        hostRef:
          name: spoke-01-host
    master-1:
      interfaces:
        primary:
          networkRef:
            name: primary
          ipAddress: 192.168.123.21
      libvirt:
        hostRef:
          name: spoke-01-host
    master-2:
      interfaces:
        primary:
          networkRef:
            name: primary
          ipAddress: 192.168.123.22
      libvirt:
        hostRef:
          name: spoke-01-host
  endpoints:
    api:
      address: 192.168.123.10
    apiInt:
      address: 192.168.123.10
    ingress:
      address: 192.168.123.11
  loadBalancers:
    default:
      endpoints:
        - api
        - apiInt
        - ingress
---
apiVersion: gitups.io/v1alpha1
kind: OCPCluster
metadata:
  name: spoke-01
spec:
  role: managed
  topology: multi-node
  infrastructureRef:
    name: spoke-01
  install:
    method: agent
  nodes:
    master-0:
      role: control-plane
    master-1:
      role: control-plane
    master-2:
      role: control-plane
