---
- name: Install cluster with openshift-install agent
  hosts: bootwright_ocp_hosts
  gather_subset:
    - "!all"
    - min
  become: true
  environment: "{{ bootwright_proxy_env | default({}) }}"

  pre_tasks:
    - name: Gather remote environment
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - env

    - name: Resolve cluster context
      ansible.builtin.import_role:
        name: context_cluster

  roles:
    - role: host_proxy
    - role: install_agent
      when: bootwright_current_cluster.ocp.install.method == 'agent'
