---
- name: Install OpenShift cluster via openshift-install agent
  hosts: gitups_ocp_hosts
  gather_subset:
    - "!all"
    - min
  become: true
  environment: "{{ gitups_proxy_env | default({}) }}"

  pre_tasks:
    - name: Gather remote-root environment for openshift-install lookup
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - env

    - name: Build cluster context
      ansible.builtin.import_role:
        name: context_cluster

  roles:
    - role: host_proxy
    - role: install_agent
      when: gitups_current_cluster.ocp.install.method == 'agent'
