---
- name: Select cluster for this host
  ansible.builtin.set_fact:
    gitups_current_cluster: "{{ gitups_clusters | selectattr('name', 'equalto', gitups_cluster_name) | first }}"
  changed_when: false

- name: Select provider for this host
  ansible.builtin.set_fact:
    gitups_current_provider: "{{ gitups_providers | selectattr('name', 'equalto', gitups_provider_name) | first }}"
  changed_when: false
  when: gitups_provider_name is defined

- name: Publish cluster context facts
  ansible.builtin.set_fact:
    gitups_cluster_ctx:
      cluster: "{{ gitups_current_cluster }}"
      provider: "{{ gitups_current_provider | default(None) }}"
  changed_when: false
