---
gitups_clis_mirror_base: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp"
gitups_clis_install_dir: "/usr/local/bin"
gitups_clis_tmp_dir: "{{ ansible_env.HOME }}/.gitups/tmp/controller-clis"
gitups_clis_packages:
  - openssh-clients
  - nmstate
  - procps-ng
