---
- name: Load base package list
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Install base host packages
  ansible.builtin.package:
    name: "{{ gitups_host_base_packages }}"
    state: present

- name: Create cluster state directory
  ansible.builtin.file:
    path: "{{ gitups_host_state_dir }}/{{ gitups_current_cluster.name }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
