package cli

import (
	"fmt"
	"io"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// Preserve the AddCommand registration order in `--help` so workflow
// commands render in usage order rather than alphabetically.
func init() { cobra.EnableCommandSorting = false }

// Command groups used in `gitups --help`. The workflow group is ordered to
// match the canonical bring-up sequence (author state → bootstrap → install
// → bootstrap GitOps); the general group collects cobra's autogenerated
// `help` and `completion` so they don't clutter the workflow listing.
const (
	groupWorkflow = "workflow"
	groupGeneral  = "general"
)

func newRootCmd(stdin io.Reader, stdout io.Writer, stderr io.Writer) *cobra.Command {
	root := &cobra.Command{
		Use:   "gitups",
		Short: "GitOps-driven OpenShift fleet provisioning",
		Long: "Gitups renders, validates, and converges versioned desired-state YAML\n" +
			"to drive OpenShift cluster lifecycle.",
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	root.SetFlagErrorFunc(func(_ *cobra.Command, err error) error {
		return failErr(2, err)
	})
	root.SetIn(stdin)
	root.SetOut(stdout)
	root.SetErr(stderr)

	root.AddGroup(
		&cobra.Group{ID: groupWorkflow, Title: "Workflow Commands:"},
		&cobra.Group{ID: groupGeneral, Title: "General Commands:"},
	)
	root.SetHelpCommandGroupID(groupGeneral)
	root.SetCompletionCommandGroupID(groupGeneral)

	addWorkflow(root,
		newInitCmd(stdout),           // 1. scaffold workspace material
		newSecretCmd(stdout, stderr), // 2. materialize secret refs
		newCheckCmd(stdout, stderr),   // 3. validate prerequisites and desired state
		newStatusCmd(stdout),          // 4. report workspace state and next step
		newRenderCmd(stdout, stderr),  // 5. render generated install files
		newApplyCmd(stdin, stdout, stderr),
		newGitopsCmd(),
	)
	return root
}

// addWorkflow adds commands under the workflow group while preserving the
// caller-supplied order so `--help` reflects the canonical usage sequence.
func addWorkflow(parent *cobra.Command, cmds ...*cobra.Command) {
	for _, c := range cmds {
		c.GroupID = groupWorkflow
		parent.AddCommand(c)
	}
}

type commonFlags struct {
	files    []string
	stateDir string
}

func addCommonFlags(cmd *cobra.Command) *commonFlags {
	cf := &commonFlags{stateDir: defaultStateDir()}
	cmd.Flags().StringArrayVarP(&cf.files, "file", "f", nil, "Gitups YAML file or directory; may be repeated (default: <state-dir>/clusters-bootstrap.git/*/gitups)")
	cmd.Flags().StringVar(&cf.stateDir, "state-dir", cf.stateDir, "generated state directory (env: GITUPS_STATE_DIR)")
	return cf
}

func showSubcommandFlagsInHelp(cmd *cobra.Command) {
	defaultHelp := cmd.HelpFunc()
	cmd.SetHelpFunc(func(c *cobra.Command, args []string) {
		defaultHelp(c, args)
		if c != cmd {
			return
		}
		merged := pflag.NewFlagSet("subcommand", pflag.ContinueOnError)
		for _, sub := range c.Commands() {
			if !sub.IsAvailableCommand() {
				continue
			}
			sub.LocalFlags().VisitAll(func(f *pflag.Flag) {
				if f.Name == "help" || merged.Lookup(f.Name) != nil {
					return
				}
				merged.AddFlag(f)
			})
		}
		usages := merged.FlagUsages()
		if usages == "" {
			return
		}
		fmt.Fprintf(c.OutOrStdout(), "\nSubcommand Flags:\n%s", usages)
	})
}
