---
- name: Load libvirt package list
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Install libvirt host packages
  ansible.builtin.package:
    name: "{{ bootwright_host_libvirt_packages }}"
    state: present

- name: Start libvirt service
  ansible.builtin.service:
    name: "{{ bootwright_host_libvirt_libvirt_service }}"
    state: started
    enabled: true
