---
- name: Validate Gitups lowest-layer infrastructure
  hosts: gitups_infra_hosts
  gather_facts: true
  become: false

  pre_tasks:
    - name: Select cluster infrastructure for current host
      ansible.builtin.set_fact:
        gitups_current_cluster: "{{ gitups_clusters | selectattr('name', 'equalto', gitups_cluster_name) | first }}"
      changed_when: false

  roles:
    - role: network_external_validate
      when: gitups_current_cluster.network.nameResolution.mode == 'external' or gitups_current_cluster.network.loadBalancer.external | default(false) | bool
