---
- name: Tear down OpenShift cluster install state
  hosts: gitups_ocp_hosts
  gather_facts: false
  become: true
  environment: "{{ gitups_proxy_env | default({}) }}"

  pre_tasks:
    - name: Select cluster infrastructure for current host
      ansible.builtin.set_fact:
        gitups_current_cluster: "{{ gitups_clusters | selectattr('name', 'equalto', gitups_cluster_name) | first }}"
      changed_when: false

    - name: Select infrastructure provider for current host
      ansible.builtin.set_fact:
        gitups_current_provider: "{{ gitups_providers | selectattr('name', 'equalto', gitups_provider_name) | first }}"
      changed_when: false

  tasks:
    - name: Build proxy facts for downstream tasks
      ansible.builtin.import_role:
        name: host_proxy
        tasks_from: facts

    - name: Apply OCP destroy agent role
      ansible.builtin.import_role:
        name: ocp_destroy_agent
      when: gitups_current_cluster.ocp.install.method == 'agent'
