apiVersion: gitups.io/v1alpha1
kind: Environment
metadata:
  name: lab
spec:
  baseDomain: example.com
  ocpInstallType: connected
  secrets:
    openshift-pull-secret:
      file: ~/.gitups/secrets/openshift-pull-secret
    cluster-admin-key:
      file: ~/.ssh/gitups-ssh-key.pub
    lab-provider-key:
      file: ~/.ssh/gitups-ssh-key
    lab-bmc-credentials:
      generated:
        credentials:
          username: admin
  openshift:
    release:
      channel: stable-4.21
      version: 4.21.12
