apiVersion: gitups.io/v1alpha1
kind: InfrastructureProvider
metadata:
  name: qemu-redfish-provider
spec:
  hosts:
    qemu-host:
      ssh:
        address: 192.168.10.11
        keyRef:
          name: qemu-host-ssh
      capabilities:
        - libvirt
        - hosts-file
  machine:
    libvirt:
      hostRefs:
        - name: qemu-host
      bmcEmulation:
        enabled: true
        protocol: redfish
        auth:
          credentialRef:
            name: qemu-redfish-bmc
      machineProfiles:
        sno:
          cpu: 8
          memoryMiB: 22528
          diskGiB: 120
  loadBalancer:
    haProxy:
      hostRef:
        name: qemu-host
  nameResolution:
    hostsFile:
      hostRefs:
        - name: qemu-host
